development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://yvacwtdcwrxich:onp9d3kL3zbBYE22O4kgDiPFhs@ec2-54-227-240-164.compute-1.amazonaws.com:5432/d28v06qc48neei
